# Generated by Django 2.1.2 on 2018-10-09 15:13

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EnergyValue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('protein', models.IntegerField(validators=[django.core.validators.MaxValueValidator(3)])),
                ('fat', models.IntegerField(validators=[django.core.validators.MaxValueValidator(3)])),
                ('carbohydrate', models.IntegerField(validators=[django.core.validators.MaxValueValidator(3)])),
                ('ccal', models.IntegerField(validators=[django.core.validators.MaxValueValidator(4)])),
            ],
        ),
        migrations.CreateModel(
            name='Pizza',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(default='static/photos_def/pizza/pizza_def.jpg', upload_to='upload_photos/pizza_photo')),
                ('name', models.CharField(max_length=30)),
                ('ingredients', models.TextField()),
                ('cost', models.IntegerField()),
                ('energ_val', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='home_app.EnergyValue')),
            ],
        ),
    ]
