# Generated by Django 2.1.2 on 2018-10-10 16:31

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home_app', '0002_auto_20181010_1927'),
    ]

    operations = [
        migrations.AlterField(
            model_name='energyvalue',
            name='carbohydrate',
            field=models.IntegerField(validators=[django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='energyvalue',
            name='ccal',
            field=models.IntegerField(validators=[django.core.validators.MaxValueValidator(5000)]),
        ),
        migrations.AlterField(
            model_name='energyvalue',
            name='fat',
            field=models.IntegerField(validators=[django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='energyvalue',
            name='protein',
            field=models.IntegerField(validators=[django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='pizza',
            name='energ_val',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='home_app.EnergyValue'),
        ),
    ]
